#!/usr/bin/env bash

set -euo pipefail

declare BASE_IMAGE="hkjn/golang:$(uname -m)-tip"
declare BUILD_DIR="$(mktemp -d)"
declare BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${BASE}

echo "Building in $BASE_IMAGE.."
sed "s|{{ARG_FROM}}|${BASE_IMAGE}|g" Dockerfile.build > $BUILD_DIR/Dockerfile
cp -r *.go redirector vendor $BUILD_DIR

docker build -t decenter-build $BUILD_DIR
docker run --name decenter-build decenter-build
rm -rf bin/
docker cp decenter-build:/home/go/bin/ .
docker rm decenter-build
mv -v bin/* .
