FROM {{ARG_FROM}}

ENV GOOS=linux \
    CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/decenter.world

COPY ["server.go", "./"]
COPY ["redirector/", "./redirector/"]
COPY ["vendor/", "./vendor/"]

RUN sh -c "GOARCH=amd64 go build -o ~/bin/decenter_world_x86_64 ./" && \
    sh -c "GOARCH=amd64 go build -o ~/bin/decenter_redirector_x86_64 ./redirector/"
WORKDIR /home/go/bin
CMD ["-c", "echo", "Binaries available in $(pwd): $(ls decenter_*)"]


