FROM {{ARG_FROM}}

ENV GOOS=linux \
    CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/decenter.world

USER root
RUN apk add --no-cache musl-dev
USER go

COPY ["server.go", "./"]
COPY ["redirector/", "./redirector/"]

RUN sh -c "GOARCH=amd64 go build -o ~/bin/decenter_world_x86_64 ./" && \
    sh -c "GOARCH=amd64 go build -o ~/bin/decenter_redirector_x86_64 ./redirector/"
WORKDIR /home/go/bin
CMD echo "Binaries available in $(pwd): $(ls decenter_*)"


